Injected dependencies by using setter injection
Twenytoo/magic8ball_Y pull request #3
Opened 2021-11-07 16:41 UTC by Twenytoo

Deleted static methods and singletone

2021-11-08 16:46 UTC, ios-school-yalantis requested changes

2021-11-08 16:46 UTC, ios-school-yalantis commented on MagicEightBall/View Controllers/ViewController.swift
> +    }
контроллер не должен сам себе создавать зависимости

2021-11-08 16:46 UTC, ios-school-yalantis commented on MagicEightBall/View Controllers/SettingsViewController.swift
>          answers = realm.objects(Answer.self)
работы с realm не должно остаться в `ViewController`ах, это касается обоих контроллеров

2021-11-08 16:46 UTC, ios-school-yalantis commented on MagicEightBall/View Controllers/SettingsViewController.swift
>      }
зависимости должны быть созданы из вне

2021-11-10 17:31 UTC, ios-school-yalantis approved these changes
после исправления последних комментариев можно мержить, без повторной проверки

2021-11-10 17:31 UTC, ios-school-yalantis commented on MagicEightBall/View Controllers/ViewController.swift
> +    func setStorageManager (storageManager: StorageService) {
лишние пробелы после названия функции

2021-11-10 17:31 UTC, ios-school-yalantis commented on MagicEightBall/View Controllers/ViewController.swift
> +    @IBAction func cancelAction (_ segue: UIStoryboardSegue) {}
пустая функция, может лучше удалить?

2021-11-10 20:34 UTC, Twenytoo commented on MagicEightBall/View Controllers/ViewController.swift
> +    @IBAction func cancelAction (_ segue: UIStoryboardSegue) {}
К ней протянут Unwind segue от кнопки Cancel, что бы выйти из второго контроллера

2021-11-10 20:37 UTC, merged